# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	allocator-api2@0.2.21
	anyhow@1.0.97
	autocfg@1.4.0
	bitflags@2.9.0
	cassowary@0.3.0
	castaway@0.2.3
	cc@1.2.17
	cfg-if@1.0.0
	compact_str@0.8.1
	crossterm@0.28.1
	crossterm_winapi@0.9.1
	darling@0.20.11
	darling_core@0.20.11
	darling_macro@0.20.11
	either@1.15.0
	equivalent@1.0.2
	errno@0.3.10
	fallible-iterator@0.3.0
	fallible-streaming-iterator@0.1.9
	fnv@1.0.7
	foldhash@0.1.5
	hashbrown@0.15.2
	hashlink@0.10.0
	heck@0.5.0
	ident_case@1.0.1
	indoc@2.0.6
	instability@0.3.7
	itertools@0.13.0
	itoa@1.0.15
	libc@0.2.171
	libsqlite3-sys@0.32.0
	linux-raw-sys@0.4.15
	lock_api@0.4.12
	log@0.4.27
	lru@0.12.5
	mio@1.0.3
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	paste@1.0.15
	pkg-config@0.3.32
	proc-macro2@1.0.94
	quote@1.0.40
	ratatui@0.29.0
	redox_syscall@0.5.10
	rusqlite@0.34.0
	rustix@0.38.44
	rustversion@1.0.20
	ryu@1.0.20
	scopeguard@1.2.0
	shlex@1.3.0
	signal-hook-mio@0.2.4
	signal-hook-registry@1.4.2
	signal-hook@0.3.17
	smallvec@1.14.0
	spin@0.10.0
	static_assertions@1.1.0
	strsim@0.11.1
	strum@0.26.3
	strum_macros@0.26.4
	syn@2.0.100
	unicode-ident@1.0.18
	unicode-segmentation@1.12.0
	unicode-truncate@1.1.0
	unicode-width@0.1.14
	unicode-width@0.2.0
	vcpkg@0.2.15
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.52.0
	windows-sys@0.59.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
"

RUST_MIN_VER="1.85.0"

inherit cargo

DESCRIPTION="SQLite database space usage viewer"
HOMEPAGE="https://github.com/krypt0nn/vinolite"
SRC_URI="
	https://github.com/krypt0nn/vinolite/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="GPL-3"
# Dependent crate licenses
LICENSE+="
	MIT Unicode-3.0 ZLIB
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"

